# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b37852b9a344b0f140c8608c23c4ce3a"
name = "qrcode-test"
handle = "qrcode-test-13"
application_url = "https://shopify-sample-app-beta.vercel.app/"
embedded = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://shopify-sample-app-beta.vercel.app/api/auth" ]

[pos]
embedded = false
